### ISSUE TITLE
Error with regex into pem.js

### ISSUE THREAD

**Issue by percenuage** [AzureAD/passport-azure-ad#121] opened 2016-06-13 14:58 UTC
I've an error into _pem.js_ when I run  my application with passport. I read your file and I notice you added some regex verification (certificate and private key). : 
>  ('str' must be of type "String", actually is object)

The function `getFirstCapturingGroup(str, regex)` return null. In fact, `if (!Array.isArray(matches) || matches.length !== 1)` is true because the matches is an array with length of 2.

I try the same code with your previous version (1.4.5) and everything works well :)

Could you help me to resolve this problem ?

Thank you

**Comment by brandwe** [comment] 2016-06-15 20:55
Looks like a regression. I'll take a look.

**Comment by lovemaths** [comment] 2016-06-16 23:50
This is a bug. matches should have length 2 and the getFirstCapturingGroup should return matches[1].  In the getFirstCapturingGroup code, make the following change should make it work: 

 if (!Array.isArray(matches) || matches.length !== 1) {  <====  change 1 to 2
    return null;
  }
  return matches[0];   <===== change 0 to 1

**Comment by lovemaths** [comment] 2016-06-20 16:54
Fixed in dev branch.

**Closed by lovemaths** 2016-06-20 16:54 UTC
Labels: bug, investigate, triaged
