### ISSUE TITLE
Inconsistent profile information?

### ISSUE THREAD

**Issue by RalphSleigh** [AzureAD/passport-azure-ad#384] opened 2018-05-20 13:29 UTC
Hi

I may be doing it wrong, but I can't get the profile information to work consistently. I am trying to add a series of social login buttons to my app and I am setting it up like so:

```

version: 3.0.12

passport.use(new OIDCStrategy({
        identityMetadata: 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration',
        clientID: ....,
        responseType: 'id_token',
        responseMode: 'form_post',
        redirectUrl: .....,
        allowHttpForRedirectUrl: true,
        clientSecret: .....,
        validateIssuer: false,
        isB2C: false,
        issuer: null,
        passReqToCallback: false,
        scope: ['profile','email'],
        useCookieInsteadOfSession: false,
    },
```

Now in the case when I log in using a personal hotmail account the e-mail address ends up in:

profile._json.email

With an organisational account:

e-mail is in profile._json.preferred_username

I can take account of this in my code, but every other passport login strategy is filling in  profile.emails[0].value like the passport docs say they should.

**Comment by brandwe** [comment] 2019-05-15 04:32
Hey @RalphSleigh thanks for the pull request. The issue is that email might not always be the preferred username. Someone can change their domain alias but have a different email address. For instance, you can have an email of firstname.lastname@company.com, but your preferred username might be lastname@company.com.

**Comment by GriFlo** [comment] 2019-08-01 15:40
Hey @brandwe. Could you please at least merge the part `emails: src.emails || [{value: src.email} ]`? because the emails property isn't set at all for now. (I tried it with personal and business accounts. )

**Comment by pkanher617** [comment] 2021-03-19 22:02
Closing for now. We are in the process of moving the `passport-azure-ad` to our monorepo. If you have any further questions please open an issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose).

**Closed by pkanher617** 2021-03-19 22:02 UTC
