### ISSUE TITLE
How to Debug "Invalid state received in the request"

### ISSUE THREAD

**Issue by CodeWilliamson** [AzureAD/passport-azure-ad#462] opened 2020-01-12 00:55 UTC
Hi All,

We just went live with an application the uses express-session (stored in mongo db) with passport (OIDCStrategy with b2c login policy). We tested everything we could think of around authentication and everything seemed good but we have 1 user that keeps getting a failed login with the message: "authentication failed due to: In collectInfoFromReq: invalid state received in the request".

We are using session stored in mongo and not encrypted cookies on client. It's hard for me to debug because I don't have a direct support line with user yet. How can I compare the state saved in session by the passport library to the state it sends back? I tried custom middleware but the state gets generated inside passport which I cannot see. Any thoughts?

Mark

**Comment by bburhans** [comment] 2020-01-13 07:34
Definitely attach a debugger or add debug-level log lines. This module uses bunyan, so if you add a bunyan logger to your app with the appropriate level, it'll pick up some logs from the dependency. If you don't have too much traffic, you can even just log out every login request `req` including the body; that will allow you to verify that a state and nonce are coming back as expected.

That said, I just spent a considerable amount of time hunting down a cookie-based issue for some browsers; by any chance, is this user on an older iPhone (iOS 12) or a Mac that's not on the latest OS version? It manifests as the exact "invalid state" message you described. The cookie problem was addressed in the passport-azure-ad codebase, but with a flaw that neutered it that I had to patch out with `patch-package`.

To see if this is the problem, you might use access logs (morgan, apache2, nginx, ???) to verify the user agent of the failed request that eventually generated the 401 or other error page; the affected browsers contain these strings, although the recent desktop versions of Chrome/Chromium are not affected even if these match:
- CPU iPhone OS 12
- iPad; CPU OS 12
- Macintosh; Intel Mac OS X 10_14
- Chrome/5
- Chrome/6

**Comment by CodeWilliamson** [comment] 2020-01-13 12:56
I can verify that the user having the issue is on Windows 10 using latest Chrome. I don't think it's a cookie issue because I'm using stored session on Mongo. The hardest part is that it's only occurring for 1 user at the moment but I want to get to the bottom of the issue before it affects other users (we are in BETA).

**Comment by bencooper222** [comment] 2020-02-22 20:34
@DadWilliamson did you ever figure it out? We're having the same issue with a Mongo store

**Comment by CodeWilliamson** [comment] 2020-02-22 22:14
> @DadWilliamson did you ever figure it out? We're having the same issue with a Mongo store

Unfortunately no, the problem user stopped having the problem all of a sudden. I suspect it was some issue with a cookie not matching the session. I’m baffled.

**Comment by bencooper222** [comment] 2020-02-23 22:05
Yeah our issue is because Microsoft is being weird about same site cookies on localhost. It considers localhost:8080 and 8081 to be different so the express-session cookie kept resetting. GitHub and Google didn't have any issue so I assume it's just some Microsoft weirdness.

**Comment by ultimate-tester** [comment] 2020-08-05 13:58
I am experiencing the exact same issue, only for 1 user specifically on IE on a Windows Server. Reproducing the problem elsewhere seems to be impossible. All attempts done are in incognito mode to make sure there's no interfering sessions/cookies. Did anyone run into this again and solved it? The whole website is running on port 443 (HTTPS) so the same-site shouldn't be it (and also that would be reproducible)

**Comment by CodeWilliamson** [comment] 2020-08-19 20:54
I'm in another situation where I'm getting this error and I think clearing cookies and cache will get rid of it but I don't want to because I would rather debug the situation. I'm lost though as to how to debug. Any ideas? I'm authenticating fine with Azure AD but when it sends request back to my localhost (in dev mode here), it says "authentication failed due to: In collectInfoFromReq: invalid state received in the request".

**Comment by CodeWilliamson** [comment] 2020-08-20 00:31
Did some more digging and found out that the session data in the POST callback to passport doesn't contain the key or data it's looking for. Here is an example of what is in my session in the POST callback:  

{"cookie":{"originalMaxAge":21600000,"expires":"2020-08-20T06:26:24.397Z","httpOnly":true,"path":"/"}}

It is looking for a tuple containing the REAL session data based on the state and it's not in the overall session data. So I wonder where it is being dropped... ANY ideas?

**Comment by ernie58** [comment] 2020-08-26 21:03
Hi @CodeWilliamson We have the same problem, did you found a solution

**Comment by CodeWilliamson** [comment] 2020-08-26 23:16
> Hi @CodeWilliamson We have the same problem, did you found a solution

Nope not yet but I'm suspecting it's an issue with how the session is handled between express and passport, perhaps? It looks like a new session is created sometimes after the redirect from authentication which doesn't seem right. When I clear all sessions from the mongo store, it fixes the issue.

**Comment by ccare** [comment] 2020-08-31 19:49
I've come across this error in relation to SameSite cookie values. Code that used to work, no longer seems to, and I wonder if it's because the default behaviour of `SameSite` has changed?

With the express session cookie set to use `SameSite=lax` I get this error, with `SameSite=none` it's fine. So I wonder if the emergence of this error might be due to Chrome 80 and the `lax` becoming the new default. I need look more into why I'm only seeing this for AzureAD and not other auth providers, but I think it might hinge on the fact that I'm using the form-post callback flow... maybe?

**Comment by jeffwilcox** [comment] 2020-08-31 20:00
@ccare on my team we started looking into the right approach for `SameSite` and gave up, it's a mess!

When I looked, I had the impression we'd have to modify the Express session code to do some dynamic browser identification - if it's a modern Chrome or equivalent, set SameSite to `none`, otherwise determine what to do. Yes, I think it's that the newer behavior is to not send any session info on a POST to another site.

Interested in what you learn!

**Comment by MarkusFeldmann** [comment] 2020-09-03 08:35
Hi all,
I just ran into this as well. In my case chrome did not X-Site send the connect.sid (and in fact told me so in the console and under 'issues'). What I changed do make it run was:

if(this.app.get('env') === 'development'){
            this.app.set('trust proxy', true);       
            secure = true;     
        }

        var sess = session({
            secret: 'whenthegoinggetsweiredtheweiredturnpro',
            cookie: {
                maxAge: 84600 * 1000,
                secure: secure,
                sameSite: 'none'
            },
            store: new MongoStore({ mongooseConnection: mongoose.connection, ttl: 86400 }),
            saveUninitialized: false,
            resave: false
        });

Then deleted the cookie, and it worked. The cookie now shows SameSite="none" and Secure = "true"

HTH

regards,
Markus

**Comment by CodeWilliamson** [comment] 2020-09-09 21:01
I have done some more digging and found out that yes on the POST callback from Azure, there's sometimes no cookie set and thus the session gets recreated in express which then screws up the rest of the auth process.

I'm trying your suggestion @MarkusFeldmann ... EDIT: It did not work for me. After randomly testing many things in many different orders, I eventually hit the bug. Right before the POST callback is called, I get this:

express-session no SID sent, generating session

**Comment by aarhusgregersen** [comment] 2021-02-10 12:14
I've recently been struggling with this too, and in the end I found that this wasn't an issue with Azure, or the `passport-azure-ad` library in particular. For us, it turned out to be the `express-session` `cookie.secure` feature, which blocked the cookie coming back from Azure, or rather the cookie that was being set based on the request. 

We can disable this option, because we don't use cookies, but store a session in LocalStorage, which holds what we need. Maybe this may help you

**Comment by jeffwilcox** [comment] 2021-02-10 15:03
@aarhusgregersen which Azure site product are you using to serve the site?

When using load balancers, you likely also need to set the Express "trust proxy" setting for secure cookies to be set. http://expressjs.com/en/guide/behind-proxies.html

**Comment by pkanher617** [comment] 2021-04-08 21:49
It appears the discussion has reached the conclusion. If you would like to continue this, I suggest creating a topic in the [discussion boards for the MSAL Javascript repository](https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions). We are working on a new version of this library and will be making updates in the [MSAL JS mono-repo](https://github.com/AzureAD/microsoft-authentication-library-for-js). Closing this for now.

**Closed as completed by pkanher617** 2021-04-08 21:49 UTC
