### ISSUE TITLE
Renew token using refresh token

### ISSUE THREAD

**Issue by ErrorPro** [AzureAD/passport-azure-ad#368] opened 2018-02-16 08:50 UTC
Hi,

I want to renew a new token using refresh_token, azure allows me to do so just calling `/token` with correct [parameters.](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oauth-code#4-refresh-the-token).
All we need to do to make it work using your library is to change [grant_type](https://github.com/AzureAD/passport-azure-ad/blob/e94c8034c75074ef5abf69390829090db8da83ca/lib/oidcstrategy.js#L1356) to `refresh_token` and pass refresh_token. 

Could you tell me please, is this feature in your feature's list and if it's there when will you add it? If it's not would it make sense If I made a PR with this feature?

**Comment by lovemaths** [comment] 2018-02-20 21:24
@ErrorPro duplicate of #297 
This is in our features list, but we are not planning to add this feature in the next few months. We haven't designed it yet, things can get complicated when refresh token expires.

**Closed by lovemaths** 2018-02-20 21:24 UTC
