### ISSUE TITLE
Question: Is it possible to use my own logging library?

### ISSUE THREAD

**Issue by yarandoo** [AzureAD/passport-azure-ad#145] opened 2016-07-13 01:48 UTC
Currently the only option I see is to specify the logging level, but I dont see any option to provide our own logging function. Would that be possible?

This will allow us to use the same format for all our application logs, and will reuse our log parsing rules, instead of having to create a new one for this specific library.

Thanks!

**Comment by jeffwilcox** [comment] 2016-07-13 05:28
+1! See also, https://github.com/AzureAD/passport-azure-ad/issues/107

**Comment by polita** [comment] 2016-07-13 19:24
Closing as this is a duplicate of #107.

**Closed by polita** 2016-07-13 19:24 UTC
Labels: question
